### ISSUE TITLE
Documentação de Contexto - Introdução

### ISSUE THREAD

**Issue by jpbarbosa44** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc#1]
A elaboração da descrição deverá conter um texto descritivo com a visão geral do projeto abordado. Inclui o contexto, o problema, os objetivos, a justificativa e o público-alvo do projeto.

**Comment by Marcelleap** [comment]
O texto foi elaborado e finalizado dia 20/03/2023. 


[Documentação de Contexto (2).pdf](https://github.com/ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc/files/11034743/Documentacao.de.Contexto.2.pdf)
