### ISSUE TITLE
Documentação de Contexto - Problema

### ISSUE THREAD

**Issue by jpbarbosa44** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc#2]
O texto deverá apresentar o problema que seu grupo buscará resolver/minimizar. No entanto, não é a hora de comentar sobre a abordagem a ser utilizada para resolvê-lo

**Comment by Marcelleap** [comment]
![Image](https://user-images.githubusercontent.com/92685909/226763738-1a030ff9-110b-4057-ab68-0db6498c0f18.png)
