### ISSUE TITLE
Roteiro de Testes

### ISSUE THREAD

**Issue by Marcelleap** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc#20]

**Comment by mateus-boletta** [comment]
[Roteiro de Teste.docx](https://github.com/ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc/files/11141232/Roteiro.de.Teste.docx)
