### ISSUE TITLE
Documentação de contexto - Objetivos

### ISSUE THREAD

**Issue by jpbarbosa44** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc#3]
Aqui você deve descrever os objetivos do trabalho que será realizado pelo grupo indicando qual é o objetivo geral que se busca atingir para solucionar/minimizar o problema apresentado acima.

Apresente também alguns (pelo menos 2) objetivos específicos dependendo de onde você vai querer concentrar a sua prática investigativa, ou como você vai aprofundar no seu trabalho.

**Comment by Marcelleap** [comment]
![Image](https://user-images.githubusercontent.com/92685909/226763416-343ebd0d-681d-4464-8034-1778e7328848.png)
