### ISSUE TITLE
Documentação de contexto - Justificativa

### ISSUE THREAD

**Issue by jpbarbosa44** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc#4]
Descreva a importância ou a motivação para trabalhar com o tema escolhido. Indique as razões pelas quais vocês escolheram seus objetivos específicos. Aproveite para "quantificar" o problema. Utilize dados, pesquisas etc que justifiquem porque é importante resolver/minimizar o problema.

O grupo de trabalho pode também fazer uso de questionários, entrevistas e dados estatísticos, que podem ser apresentados, com o objetivo de esclarecer detalhes do problema que será abordado pelo grupo, mas não se esqueça, de citar em seu texto todas as referências que forem utilizadas seguindo os padrões da ABNT e também, de incluir tais referências no documento das Referências bibliográficas.

**Comment by Marcelleap** [comment]
![Image](https://user-images.githubusercontent.com/92685909/226764031-f7f9d67d-1612-482b-a2a1-585f221369d0.png)
