### ISSUE TITLE
Especificação do Projeto

### ISSUE THREAD

**Issue by jpbarbosa44** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc#7]
Definição do problema e ideia de solução a partir da perspectiva do usuário. É composta pela definição do diagrama de personas (identifiquem, no mínimo, 2 personas), histórias de usuários (identifiquem, no mínimo, 3 histórias de usuários por persona), requisitos funcionais, requisitos não funcionais e artefatos produzidos para levantamento de dados).

**Comment by Marcelleap** [comment]
Finalizado dia 21/03/2023



[Especificação do Projeto.pdf](https://github.com/ICEI-PUC-Minas-PPC-CC/ppc-cc-2023-1-ment2-noite-palestra-cc/files/11034809/Especificacao.do.Projeto.pdf)
